// Code generated by goyacc -o gram.go -p yy gram.y. DO NOT EDIT.

//line gram.y:2
package parser

import __yyfmt__ "fmt"

//line gram.y:2

type YpParser yyParser

func NewYpParser() YpParser {
	return yyNewParser()
}

//line gram.y:15
type yySymType struct {
	yys      int
	str      string
	int      int
	node     Node
	nodeList []Node
	bool     bool
}

const SAY = 57346
const HELLO = 57347
const SHOW = 57348
const COPY = 57349
const WITH = 57350
const TOPENBR = 57351
const TCLOSEBR = 57352
const TCOMMA = 57353
const FALSE_P = 57354
const TRUE_P = 57355
const SELECT = 57356
const FROM = 57357
const WHERE = 57358
const ORDER = 57359
const BY = 57360
const SORT = 57361
const ASC = 57362
const DESC = 57363
const GROUP = 57364
const KURT = 57365
const KOBAIN = 57366
const STOP = 57367
const SYSTEM = 57368
const SCONST = 57369
const IDENT = 57370
const ICONST = 57371
const TEQ = 57372
const TSEMICOLON = 57373

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SAY",
	"HELLO",
	"SHOW",
	"COPY",
	"WITH",
	"TOPENBR",
	"TCLOSEBR",
	"TCOMMA",
	"FALSE_P",
	"TRUE_P",
	"SELECT",
	"FROM",
	"WHERE",
	"ORDER",
	"BY",
	"SORT",
	"ASC",
	"DESC",
	"GROUP",
	"KURT",
	"KOBAIN",
	"STOP",
	"SYSTEM",
	"SCONST",
	"IDENT",
	"ICONST",
	"TEQ",
	"TSEMICOLON",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 37

var yyAct = [...]int8{
	33, 32, 13, 7, 25, 8, 11, 15, 23, 18,
	16, 17, 26, 27, 21, 31, 19, 30, 14, 12,
	1, 22, 10, 20, 9, 24, 29, 28, 5, 6,
	4, 3, 2, 0, 0, 0, 34,
}

var yyPact = [...]int16{
	-1, -1000, -29, -1000, -1000, -1000, -1000, 13, -21, -16,
	-13, -18, -1000, -1000, -1000, -1000, -1000, -1000, 8, 5,
	-1000, -24, 2, -1000, -12, -1000, -1000, -24, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 32, 31, 30, 29, 28, 28, 8, 27, 26,
	25, 23, 21, 20, 19,
}

var yyR1 = [...]int8{
	0, 13, 14, 14, 6, 6, 1, 1, 1, 1,
	1, 2, 3, 4, 11, 12, 12, 7, 8, 8,
	8, 8, 9, 9, 10, 5, 5,
}

var yyR2 = [...]int8{
	0, 2, 1, 0, 1, 1, 1, 1, 1, 1,
	0, 2, 2, 4, 3, 1, 3, 2, 1, 1,
	1, 0, 1, 1, 1, 2, 2,
}

var yyChk = [...]int16{
	-1000, -13, -1, -2, -3, -5, -4, 4, 6, 25,
	23, 7, -14, 31, 5, 28, 26, 24, 27, 8,
	-11, 9, -12, -7, -10, 28, 10, 11, -8, -9,
	29, 27, 13, 12, -7,
}

var yyDef = [...]int8{
	10, -2, 3, 6, 7, 8, 9, 0, 0, 0,
	0, 0, 1, 2, 11, 12, 25, 26, 0, 0,
	13, 0, 0, 15, 21, 24, 14, 0, 17, 18,
	19, 20, 22, 23, 16,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:74
		{
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:75
		{
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:79
		{
			yyVAL.str = yyDollar[1].str
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:80
		{
			yyVAL.str = yyDollar[1].str
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:86
		{
			setParseTree(yylex, yyDollar[1].node)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:89
		{
			setParseTree(yylex, yyDollar[1].node)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:92
		{
			setParseTree(yylex, yyDollar[1].node)
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:95
		{
			setParseTree(yylex, yyDollar[1].node)
		}
	case 10:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:97
		{
			yyVAL.node = nil
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:100
		{
			yyVAL.node = &SayHelloCommand{}
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:104
		{
			yyVAL.node = &ShowCommand{
				Type: yyDollar[2].str,
			}
		}
	case 13:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:112
		{
			yyVAL.node = &CopyCommand{
				Path:    yyDollar[2].str,
				Options: yyDollar[4].nodeList,
			}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:120
		{
			yyVAL.nodeList = yyDollar[2].nodeList
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:124
		{
			yyVAL.nodeList = []Node{yyDollar[1].node}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:128
		{
			yyVAL.nodeList = append(yyDollar[1].nodeList, yyDollar[3].node)
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:135
		{
			yyVAL.node = &Option{
				Name: yyDollar[1].str,
				Arg:  yyDollar[2].node,
			}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:144
		{
			yyVAL.node = &AExprBConst{Value: yyDollar[1].bool}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:145
		{
			yyVAL.node = &AExprIConst{Value: yyDollar[1].int}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:146
		{
			yyVAL.node = &AExprSConst{Value: yyDollar[1].str}
		}
	case 21:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:147
		{
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:151
		{
			yyVAL.bool = true
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:152
		{
			yyVAL.bool = false
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:157
		{
			yyVAL.str = yyDollar[1].str
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:161
		{
			yyVAL.node = &KKBCommand{}
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:164
		{
			yyVAL.node = &KKBCommand{}
		}
	}
	goto yystack /* stack new state and value */
}
