name: Pull request

on:
  pull_request:
    branches: "*"
  push:
    branches:
      - "master"
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: open-gpdb/gpdb
          ref: OPENGPDB_STABLE

      - name: set PR ref
        if: ${{github.event_name == 'pull_request'}}
        run: echo "GITHUB_REF=${{github.head_ref}}" >> $GITHUB_ENV

      - name: set push ref
        if: ${{github.event_name == 'push'}}
        run: echo "GITHUB_REF=${{github.ref_name}}" >> $GITHUB_ENV

      - name: Setup S3
        run: |
          docker network create -d bridge yezzey_test_network
          docker run -p 9000:9000 \
                      --name s3_gpyezzey \
                      --network yezzey_test_network \
                      -d -e "MINIO_ROOT_USER=some_key" \
                      -e "MINIO_ROOT_PASSWORD=some_key" \
                      quay.io/minio/minio server /data
          sleep 2s
          docker exec s3_gpyezzey mc alias set myminio http://localhost:9000 some_key some_key
          docker exec s3_gpyezzey mc mb myminio/test-bucket-yezzey

      - name: Build
        run: docker build . --file docker/yezzey/Dockerfile --tag yezzey:1.0 --build-arg accessKeyId=some_key --build-arg secretAccessKey=some_key --build-arg bucketName=gpyezzey --build-arg s3endpoint=http:\\/\\/$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' s3_gpyezzey):9000

      - name: Run Docker
        shell: bash
        run: |
          docker run yezzey:1.0

