name: Run yezzey integration tests

on:
  pull_request:
    branches: "*"
  push:
    branches:
      - "master"
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: open-gpdb/gpdb
          ref: OPENGPDB_STABLE

      - name: set PR ref
        if: ${{github.event_name == 'pull_request'}}
        run: echo "GITHUB_REF=${{github.head_ref}}" >> $GITHUB_ENV

      - name: set push ref
        if: ${{github.event_name == 'push'}}
        run: echo "GITHUB_REF=${{github.ref_name}}" >> $GITHUB_ENV

      - name: Build
        run: docker compose -f docker/yezzey/docker-compose.yaml build

      - name: Run Docker
        shell: bash
        run: docker compose -f docker/yezzey/docker-compose.yaml run --remove-orphans yezzey

